version: 2

models:
  - name: dim_album
    description: "Album dimension table"
    columns:
      - name: id
        description: "The primary key for the album dimension table"
        data_tests:
          - unique
          - not_null

      - name: album_id
        description: "The primary key for the source album table"
        data_tests:
          - unique
          - not_null

      - name: name
        description: "Album's name"
        data_tests:
          - not_null

      - name: release_date
        description: "Album's release date"
        data_tests:
          - not_null

      - name: total_tracks
        description: "Album's total tracks"
        data_tests:
          - not_null

  - name: dim_date
    description: "Date dimension table"
    columns:
      - name: date_id
        description: "The primary key for the date dimension table"
        data_tests:
          - unique
          - not_null

      - name: date
        description: "Date in YYYY-MM-DD format"
        data_tests:
          - not_null

      - name: month
        description: "Date's month in integer format"
        data_tests:
          - not_null

      - name: year
        description: "Date's year in integer format"
        data_tests:
          - not_null